version: '3.7'

services:
  firmware:
    image: qmkfm/base_container:latest
    entrypoint: sleep infinity
    volumes:
        - ../:/qmk_firmware
        - ./config:/root/.config/qmk
    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
